{"name": "Проверка передачи некорректных данных при авторизации", "status": "broken", "statusDetails": {"message": "AttributeError: module 'helpers' has no attribute 'register_new_courier_and_return_login_password'", "trace": "@pytest.fixture\n    def registered_courier():\n>       login, password, first_name = helpers.register_new_courier_and_return_login_password()\nE       AttributeError: module 'helpers' has no attribute 'register_new_courier_and_return_login_password'\n\nconftest.py:9: AttributeError"}, "parameters": [{"name": "invalid_data", "value": "'password'"}], "start": 1719338438361, "stop": 1719338438361, "uuid": "025159a4-a2eb-4ca4-8702-18bb5cea75f9", "historyId": "3295d88e77ed245ded12641e2e9c447a", "testCaseId": "06a91b9c38150f72d251736af0cf6230", "fullName": "tests.test_courier_login.TestLoginCourier#test_courier_login_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "NB-ISC-14346"}, {"name": "thread", "value": "33197-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}